// Generated by CoffeeScript 1.7.1
(function() {
  exports.index = function(req, res) {
    res.render("index", {
      title: "Express"
    });
    return res.render('index');
  };

}).call(this);

//# sourceMappingURL=index.map
